name: Check for new photoprism release

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check_for_new_release:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - run: pacman -Sy --noconfirm base-devel git pacman-contrib github-cli git libvips
    - run: |
        git config --global --add safe.directory /__w/pkgbuilds/pkgbuilds
        git config --global user.name "Update Bot"
        git config --global user.email "133871599+thomas-pkgbuild-dependabot@users.noreply.github.com"

    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.PAT }}

    - run: ./check-for-update.sh
      working-directory: ./photoprism-bin
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        EUID: 1 # Trick makepkg into thinking it is not running as root
      shell: bash