name: Check for new photoprism release

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check_for_new_release:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - run: ./check-for-update.sh
      working-directory: ./photoprism-bin
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      shell: bash