name: Check for new photoprism release

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check_for_new_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - run: ./check_for_update.sh
      working-directory: ./photoprism
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
