name: Check for new photoprism release

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check_for_new_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - run: |
        NEW_RELEASE=$(./update-pkgbuild-new-version.sh)

        echo "version=$NEW_RELEASE" >> "$GITHUB_OUTPUT"
      id: new-release
      working-directory: ./photoprism-bin
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - uses: heyhusen/archlinux-package-action@v2.2.1
      with:
        pkgrel: 0
        updpkgsums: true
        srcinfo: true
        path: ./photoprism-bin

    - uses: peter-evans/create-pull-request@v6
      with:
        branch: bump-photoprism-${{ steps.new-release.outputs.version }}
        title: Upgrade photoprism to ${{ steps.new-release.outputs.version }}
        token: ${{ secrets.PAT }}
        reviewers: thomaseizinger