name: Release photoprism

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        name: aur
        config: |
          Host aur
            HostName aur.archlinux.org
            User aur
            IdentityFile ~/.ssh/aur

    - run:
        git clone https://github.com/eli-schwartz/aurpublish;
        sudo install -m755 aurpublish/aurpublish.in /usr/local/bin/aurpublish;
        aurpublish photoprism;
