name: Release photoprism

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "photoprism/PKGBUILD"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Makepkg Build and Check
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: ./photoprism
        aurDeps: tensorflow115

    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
      with:
        pkgname: photoprism
        pkgbuild: photoprism/PKGBUILD
        assets: |
          photoprism/photoprism.service
          photoprism/photoprism.sysusers
          photoprism/defaults.yml
          photoprism/photoprism.tmpfiles
          photoprism/photoprism-import.service
          photoprism/photoprism-import.timer
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR package
        ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
