name: Release rust-punchr-bin

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "rust-punchr-bin/PKGBUILD"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Makepkg Build and Check
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: ./rust-punchr-bin

    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
      with:
        pkgname: rust-punchr-bin
        pkgbuild: rust-punchr-bin/PKGBUILD
        assets: |
          rust-punchr-bin/rust-punchr.service
          rust-punchr-bin/rust-punchr.sysusers
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR package
        ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
