name: Release photoprism

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "photoprism-bin/PKGBUILD"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Makepkg Build and Check
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: ./photoprism-bin

    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
      with:
        pkgname: photoprism-bin
        pkgbuild: photoprism-bin/PKGBUILD
        assets: |
          photoprism-bin/photoprism.service
          photoprism-bin/photoprism.sysusers
          photoprism-bin/defaults.yml
          photoprism-bin/photoprism.tmpfiles
          photoprism-bin/photoprism-import.service
          photoprism-bin/photoprism-import.timer
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR package
        ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
